---
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1
metadata:
  name: stalefeaturebranches.feature-branch.dmytrostriletskyi.com
spec:
  group: feature-branch.dmytrostriletskyi.com
  names:
    kind: StaleFeatureBranch
    listKind: StaleFeatureBranchList
    plural: stalefeaturebranches
    shortNames:
      - sfb
    singular: stalefeaturebranch
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          description: StaleFeatureBranch is the Schema for the stalefeaturebranches
            API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec:
              description: StaleFeatureBranchSpec defines the desired state of StaleFeatureBranch
              properties:
                afterDaysWithoutDeploy:
                  minimum: 1
                  type: integer
                checkEveryMinutes:
                  default: 30
                  minimum: 1
                  type: integer
                namespaceSubstring:
                  type: string
              required:
                - afterDaysWithoutDeploy
                - namespaceSubstring
              type: object
            status:
              description: StaleFeatureBranchStatus defines the observed state of StaleFeatureBranch
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
